<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="DataModels\Baker\" />
    <Folder Include="DataModels\Product\" />
    <Folder Include="DataModels\Ingredient\" />
    <Folder Include="DataModels\Batch\" />
    <Folder Include="DataModels\Salary\" />
    <Folder Include="DataModels\Order\" />
    <Folder Include="DataModels\Customer\" />
  </ItemGroup>

</Project>
